version: "2.1"
services:
  kong:
    image: kong:2.1
    environment:
      - "KONG_DATABASE=off"
      - "KONG_DECLARATIVE_CONFIG=/usr/local/kong/kong_config.yml"
      - "KONG_ADMIN_LISTEN=0.0.0.0:8001"
      - "KONG_PROXY_ACCESS_LOG=/dev/stdout"
      - "KONG_ADMIN_ACCESS_LOG=/dev/stdout"
      - "KONG_PROXY_ERROR_LOG=/dev/stderr"
      - "KONG_ADMIN_ERROR_LOG=/dev/stderr"
      - "KONG_NGINX_PROXY_GZIP=on"
      - "KONG_NGINX_PROXY_GZIP_TYPES=text/plain application/json text/html application/javascript"
    command: kong start
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8443:8443"
    volumes:
      - "./kong_config.yml:/usr/local/kong/kong_config.yml"